/*
 * NAPA project
 *
 * NAPA trainee assignment
 *
 * The version of the OpenAPI document: 1
 * 
 * Generated by: https://openapi-generator.tech
 */

using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Http;
using Swashbuckle.AspNetCore.Annotations;
using Swashbuckle.AspNetCore.SwaggerGen;
using Newtonsoft.Json;
using NAPAProject.Attributes;
using NAPAProject.Models;

namespace NAPAProject.Controllers
{ 
    /// <summary>
    /// 
    /// </summary>
    [ApiController]
    public class CountriesApiController : ControllerBase
    { 
        /// <summary>
        /// 
        /// </summary>
        /// <remarks>Adds a new country to the data base</remarks>
        /// <param name="addCountryRequest">Country details</param>
        /// <response code="201">Country created successfully</response>
        /// <response code="400">Invalid input or parameters.</response>
        /// <response code="500">Internal server error</response>
        [HttpPut]
        [Route("/countries")]
        [Consumes("application/json")]
        [ValidateModelState]
        [SwaggerOperation("AddCountry")]
        [SwaggerResponse(statusCode: 201, type: typeof(string), description: "Country created successfully")]
        [SwaggerResponse(statusCode: 400, type: typeof(string), description: "Invalid input or parameters.")]
        [SwaggerResponse(statusCode: 500, type: typeof(string), description: "Internal server error")]
        public virtual IActionResult AddCountry([FromBody]AddCountryRequest addCountryRequest)
        {

            //TODO: Uncomment the next line to return response 201 or use other options such as return this.NotFound(), return this.BadRequest(..), ...
            // return StatusCode(201, default);
            //TODO: Uncomment the next line to return response 400 or use other options such as return this.NotFound(), return this.BadRequest(..), ...
            // return StatusCode(400, default);
            //TODO: Uncomment the next line to return response 500 or use other options such as return this.NotFound(), return this.BadRequest(..), ...
            // return StatusCode(500, default);
            string exampleJson = null;
            exampleJson = "\"Titanic\"";
            exampleJson = "\"Error\"";
            exampleJson = "\"Error\"";
            
            var example = exampleJson != null
            ? JsonConvert.DeserializeObject<string>(exampleJson)
            : default;
            //TODO: Change the data returned
            return new ObjectResult(example);
        }

        /// <summary>
        /// 
        /// </summary>
        /// <remarks>Delete a country</remarks>
        /// <param name="name">The name for a country.</param>
        /// <response code="204">Successful delete</response>
        /// <response code="404">Country not found.</response>
        /// <response code="500">Internal server error</response>
        [HttpDelete]
        [Route("/countries/{name}")]
        [ValidateModelState]
        [SwaggerOperation("DeleteCountry")]
        [SwaggerResponse(statusCode: 404, type: typeof(string), description: "Country not found.")]
        [SwaggerResponse(statusCode: 500, type: typeof(string), description: "Internal server error")]
        public virtual IActionResult DeleteCountry([FromRoute (Name = "name")][Required][RegularExpression("^.*?$")]string name)
        {

            //TODO: Uncomment the next line to return response 204 or use other options such as return this.NotFound(), return this.BadRequest(..), ...
            // return StatusCode(204);
            //TODO: Uncomment the next line to return response 404 or use other options such as return this.NotFound(), return this.BadRequest(..), ...
            // return StatusCode(404, default);
            //TODO: Uncomment the next line to return response 500 or use other options such as return this.NotFound(), return this.BadRequest(..), ...
            // return StatusCode(500, default);

            throw new NotImplementedException();
        }

        /// <summary>
        /// 
        /// </summary>
        /// <remarks>Retrieves the names of all the countries in the data base</remarks>
        /// <response code="200">The list of all country names.</response>
        /// <response code="500">Internal server error</response>
        [HttpGet]
        [Route("/countries")]
        [ValidateModelState]
        [SwaggerOperation("GetCountries")]
        [SwaggerResponse(statusCode: 200, type: typeof(List<string>), description: "The list of all country names.")]
        [SwaggerResponse(statusCode: 500, type: typeof(string), description: "Internal server error")]
        public virtual IActionResult GetCountries()
        {

            //TODO: Uncomment the next line to return response 200 or use other options such as return this.NotFound(), return this.BadRequest(..), ...
            // return StatusCode(200, default);
            //TODO: Uncomment the next line to return response 500 or use other options such as return this.NotFound(), return this.BadRequest(..), ...
            // return StatusCode(500, default);
            string exampleJson = null;
            exampleJson = "[ \"France\", \"France\" ]";
            exampleJson = "\"Error\"";
            
            var example = exampleJson != null
            ? JsonConvert.DeserializeObject<List<string>>(exampleJson)
            : default;
            //TODO: Change the data returned
            return new ObjectResult(example);
        }

        /// <summary>
        /// 
        /// </summary>
        /// <remarks>Update a countries name</remarks>
        /// <param name="name">The name for a country.</param>
        /// <param name="body">New country name</param>
        /// <response code="204">Successful update</response>
        /// <response code="400">Invalid input or parameters.</response>
        /// <response code="404">Country not found.</response>
        /// <response code="500">Internal server error</response>
        [HttpPut]
        [Route("/countries/{name}")]
        [Consumes("application/json")]
        [ValidateModelState]
        [SwaggerOperation("GetCountryName")]
        [SwaggerResponse(statusCode: 400, type: typeof(string), description: "Invalid input or parameters.")]
        [SwaggerResponse(statusCode: 404, type: typeof(string), description: "Country not found.")]
        [SwaggerResponse(statusCode: 500, type: typeof(string), description: "Internal server error")]
        public virtual IActionResult GetCountryName([FromRoute (Name = "name")][Required][RegularExpression("^.*?$")]string name, [FromBody]string body)
        {

            //TODO: Uncomment the next line to return response 204 or use other options such as return this.NotFound(), return this.BadRequest(..), ...
            // return StatusCode(204);
            //TODO: Uncomment the next line to return response 400 or use other options such as return this.NotFound(), return this.BadRequest(..), ...
            // return StatusCode(400, default);
            //TODO: Uncomment the next line to return response 404 or use other options such as return this.NotFound(), return this.BadRequest(..), ...
            // return StatusCode(404, default);
            //TODO: Uncomment the next line to return response 500 or use other options such as return this.NotFound(), return this.BadRequest(..), ...
            // return StatusCode(500, default);

            throw new NotImplementedException();
        }

        /// <summary>
        /// 
        /// </summary>
        /// <remarks>See if a country has been visited</remarks>
        /// <param name="name">The name for a country.</param>
        /// <response code="200">If a country has been visited</response>
        /// <response code="404">Country not found.</response>
        /// <response code="500">Internal server error</response>
        [HttpGet]
        [Route("/countries/{name}")]
        [ValidateModelState]
        [SwaggerOperation("GetCountryVisited")]
        [SwaggerResponse(statusCode: 200, type: typeof(bool), description: "If a country has been visited")]
        [SwaggerResponse(statusCode: 404, type: typeof(string), description: "Country not found.")]
        [SwaggerResponse(statusCode: 500, type: typeof(string), description: "Internal server error")]
        public virtual IActionResult GetCountryVisited([FromRoute (Name = "name")][Required][RegularExpression("^.*?$")]string name)
        {

            //TODO: Uncomment the next line to return response 200 or use other options such as return this.NotFound(), return this.BadRequest(..), ...
            // return StatusCode(200, default);
            //TODO: Uncomment the next line to return response 404 or use other options such as return this.NotFound(), return this.BadRequest(..), ...
            // return StatusCode(404, default);
            //TODO: Uncomment the next line to return response 500 or use other options such as return this.NotFound(), return this.BadRequest(..), ...
            // return StatusCode(500, default);
            string exampleJson = null;
            exampleJson = "\"Error\"";
            exampleJson = "\"Error\"";
            
            var example = exampleJson != null
            ? JsonConvert.DeserializeObject<bool>(exampleJson)
            : default;
            //TODO: Change the data returned
            return new ObjectResult(example);
        }
    }
}
