import { createAction, props } from '@ngrx/store';
import { Voyage } from '../../models/voyage.model';
import { ErrorMessage } from '../../models/error-message.model';
export const loadVoyages = createAction('[Voyages] Load');
export const loadVoyagesSuccess = createAction('[Voyages] Load Success', props<{ ids: number[] }>());
export const loadVoyagesFailure = createAction('[Voyages] Load Failure', props<{ error: ErrorMessage }>());
export const loadVoyage = createAction('[Voyages] Load One', props<{ id: number }>());
export const loadVoyageSuccess = createAction('[Voyages] Load One Success', props<{ voyage: Voyage }>());
export const loadVoyageFailure = createAction('[Voyages] Load One Failure', props<{ error: ErrorMessage }>()) ;
export const addVoyage = createAction('[Voyages] Add', props<{ voyage: Voyage }>());
export const addVoyageSuccess = createAction('[Voyages] Add Success', props<{ id: number }>());
export const addVoyageFailure = createAction('[Voyages] Add Failure', props<{ error: ErrorMessage }>());
export const deleteVoyage = createAction('[Voyages] Delete', props<{ id: number }>());
export const deleteVoyageSuccess = createAction('[Voyages] Delete Success', props<{ id: number }>());
export const deleteVoyageFailure = createAction('[Voyages] Delete Failure', props<{ error: ErrorMessage }>());
export const updateArrivalPort = createAction('[Voyages] Update Arrival', props<{ id: number; port: string }>());
export const updateArrivalPortSuccess = createAction('[Voyages] Update Arrival Success', props<{ id: number; port: string }>());
export const updateArrivalPortFailure = createAction('[Voyages] Update Arrival Failure', props<{ error: ErrorMessage }>());
export const updateDeparturePort = createAction('[Voyages] Update Departure', props<{ id: number; port: string }>());
export const updateDeparturePortSuccess = createAction('[Voyages] Update Departure Success', props<{ id: number; port: string }>());
export const updateDeparturePortFailure = createAction('[Voyages] Update Departure Failure', props<{ error: ErrorMessage }>());
export const updateDate = createAction('[Voyages] Update Date', props<{ id: number; date: string }>());
export const updateDateSuccess = createAction('[Voyages] Update Date Success', props<{ id: number; date: string }>());
export const updateDateFailure = createAction('[Voyages] Update Date Failure', props<{ error: ErrorMessage }>());
export const updateStartTime = createAction('[Voyages] Update Start', props<{ id: number; startTime: string }>());
export const updateStartTimeSuccess = createAction('[Voyages] Update Start Success', props<{ id: number; startTime: string }>());
export const updateStartTimeFailure = createAction('[Voyages] Update Start Failure', props<{ error: ErrorMessage }>());
export const updateEndTime = createAction('[Voyages] Update End', props<{ id: number; endTime: string }>());
export const updateEndTimeSuccess = createAction('[Voyages] Update End Success', props<{ id: number; endTime: string }>());
export const updateEndTimeFailure = createAction('[Voyages] Update End Failure', props<{ error: ErrorMessage }>);
export {};
